language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10'

matrix:
  include:
    - python: '3.7'
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq swig python-dev libxml2-dev libxmlsec1-dev
  - 'travis_retry pip install --force-reinstall --no-binary lxml lxml'
  - 'travis_retry pip install .'
  - 'travis_retry pip install -e ".[test]"'

script:
  - 'coverage run --source=src/onelogin/saml2 --rcfile=tests/coverage.rc setup.py test'
  - 'coverage report -m --rcfile=tests/coverage.rc'
# - 'pylint src/onelogin/saml2 --rcfile=tests/pylint.rc'
#  - 'flake8 --toml-config pyproject.toml'
  - 'flake8 --ignore E226,E302,E41,E731,E501,C901,W504'
